### ISSUE TITLE
构建失败

### ISSUE THREAD

**Issue by zziyan** [HugoChanD/docker-dm#2]
ziyan@ziyan-TUF-Gaming:~/temp/docker-dm$ sudo docker build -t hugochan/dm:latest .
Sending build context to Docker daemon  1.377GB
Step 1/21 : FROM centos:7 AS base
 ---> 8652b9f0cb4c
Step 2/21 : RUN groupadd dinstall && useradd -g dinstall -m -d /home/dmdba -s /bin/bash dmdba
 ---> Using cache
 ---> 89d0a72db492
Step 3/21 : FROM base AS install
 ---> 89d0a72db492
Step 4/21 : ARG installFilesDir=/home/dmdba/install
 ---> Using cache
 ---> c790b6be3bf8
Step 5/21 : ARG installConfName=setup.xml
 ---> Using cache
 ---> 15d08744e847
Step 6/21 : COPY DMInstall.bin  ${installFilesDir}/
 ---> Using cache
 ---> a7ead25c3e35
Step 7/21 : COPY ${installConfName} ${installFilesDir}/
 ---> Using cache
 ---> 344735e3a4df
Step 8/21 : USER dmdba
 ---> Using cache
 ---> 87d522e01c7d
Step 9/21 : RUN mkdir /home/dmdba/dmdbms
 ---> Using cache
 ---> fe042b6b72a6
Step 10/21 : RUN sh ${installFilesDir}/DMInstall.bin -q ${installFilesDir}/${installConfName}
 ---> Running in 9323aef0f096
Extract install files......    
gzip: stdin: unexpected end of file
...
Exception in thread "Thread-0" java.lang.NoClassDefFoundError: com/dameng/tool/util/script/LinuxServiceShellUtil
	at com.dameng.install.cli.MainApplication$2.run(MainApplication.java:358)
Caused by: java.lang.ClassNotFoundException: com.dameng.tool.util.script.LinuxServiceShellUtil
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more
^C
ziyan@ziyan-TUF-Gaming:~/temp/docker-dm$ uname -a
Linux ziyan-TUF-Gaming 5.8.0-36-generic #40-Ubuntu SMP Tue Jan 5 21:54:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
ziyan@ziyan-TUF-Gaming:~/temp/docker-dm$ cat /etc/issue
Ubuntu 20.10 \n \l

**Comment by zziyan** [comment]
ziyan@ziyan-TUF-Gaming:~/temp/docker-dm$ sudo docker build -t hugochan/dm:latest .
Sending build context to Docker daemon  1.377GB
Step 1/21 : FROM centos:7 AS base
 ---> 8652b9f0cb4c
Step 2/21 : RUN groupadd dinstall && useradd -g dinstall -m -d /home/dmdba -s /bin/bash dmdba
 ---> Using cache
 ---> 89d0a72db492
Step 3/21 : FROM base AS install
 ---> 89d0a72db492
Step 4/21 : ARG installFilesDir=/home/dmdba/install
 ---> Using cache
 ---> c790b6be3bf8
Step 5/21 : ARG installConfName=setup.xml
 ---> Using cache
 ---> 15d08744e847
Step 6/21 : COPY DMInstall.bin  ${installFilesDir}/
 ---> Using cache
 ---> a7ead25c3e35
Step 7/21 : COPY ${installConfName} ${installFilesDir}/
 ---> Using cache
 ---> 344735e3a4df
Step 8/21 : USER dmdba
 ---> Using cache
 ---> 87d522e01c7d
Step 9/21 : RUN mkdir /home/dmdba/dmdbms
 ---> Using cache
 ---> fe042b6b72a6
Step 10/21 : RUN sh ${installFilesDir}/DMInstall.bin -q ${installFilesDir}/${installConfName}
 ---> Running in 9323aef0f096
Extract install files......    
gzip: stdin: unexpected end of file
...
Exception in thread "Thread-0" java.lang.NoClassDefFoundError: com/dameng/tool/util/script/LinuxServiceShellUtil
	at com.dameng.install.cli.MainApplication$2.run(MainApplication.java:358)
Caused by: java.lang.ClassNotFoundException: com.dameng.tool.util.script.LinuxServiceShellUtil
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more
^C
ziyan@ziyan-TUF-Gaming:~/temp/docker-dm$ uname -a
Linux ziyan-TUF-Gaming 5.8.0-36-generic #40-Ubuntu SMP Tue Jan 5 21:54:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
ziyan@ziyan-TUF-Gaming:~/temp/docker-dm$ cat /etc/issue
Ubuntu 20.10 \n \l

**Comment by zziyan** [comment]
`ziyan@ziyan-TUF-Gaming:~/temp/docker-dm$ sudo docker build -t hugochan/dm:latest .
Sending build context to Docker daemon  1.377GB
Step 1/21 : FROM centos:7 AS base
 ---> 8652b9f0cb4c
Step 2/21 : RUN groupadd dinstall && useradd -g dinstall -m -d /home/dmdba -s /bin/bash dmdba
 ---> Using cache
 ---> 89d0a72db492
Step 3/21 : FROM base AS install
 ---> 89d0a72db492
Step 4/21 : ARG installFilesDir=/home/dmdba/install
 ---> Using cache
 ---> c790b6be3bf8
Step 5/21 : ARG installConfName=setup.xml
 ---> Using cache
 ---> 15d08744e847
Step 6/21 : COPY DMInstall.bin  ${installFilesDir}/
 ---> Using cache
 ---> a7ead25c3e35
Step 7/21 : COPY ${installConfName} ${installFilesDir}/
 ---> Using cache
 ---> 344735e3a4df
Step 8/21 : USER dmdba
 ---> Using cache
 ---> 87d522e01c7d
Step 9/21 : RUN mkdir /home/dmdba/dmdbms
 ---> Using cache
 ---> fe042b6b72a6
Step 10/21 : RUN sh ${installFilesDir}/DMInstall.bin -q ${installFilesDir}/${installConfName}
 ---> Running in 9323aef0f096
Extract install files......    
gzip: stdin: unexpected end of file
...
Exception in thread "Thread-0" java.lang.NoClassDefFoundError: com/dameng/tool/util/script/LinuxServiceShellUtil
	at com.dameng.install.cli.MainApplication$2.run(MainApplication.java:358)
Caused by: java.lang.ClassNotFoundException: com.dameng.tool.util.script.LinuxServiceShellUtil
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more
^C
ziyan@ziyan-TUF-Gaming:~/temp/docker-dm$ uname -a
Linux ziyan-TUF-Gaming 5.8.0-36-generic #40-Ubuntu SMP Tue Jan 5 21:54:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
ziyan@ziyan-TUF-Gaming:~/temp/docker-dm$ cat /etc/issue
Ubuntu 20.10 \n \l
`
